app:
  name: hotel


server:
  port: 8083  # Port for the hotel service

spring:
  application:
    name: hotel
  datasource:
    url: jdbc:mysql://localhost:3306/finess-demo?useSSL=false&serverTimezone=UTC
    username: root
    password: kritam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    register-with-eureka: true
    fetch-registry: true